---
title: C6320 | Dokumentace Microsoftu
ms.custom: ''
ms.date: 2018-06-30
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 12
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: f07ca6bdc7300a4029caf272c80d752997884d68
ms.sourcegitcommit: 55f7ce2d5d2e458e35c45787f1935b237ee5c9f8
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 08/22/2018
ms.locfileid: "42670504"
---
# <a name="c6320"></a>C6320
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Nejnovější verzi tohoto tématu můžete najít v [C6320](https://docs.microsoft.com/visualstudio/code-quality/c6320).  
  
upozornění C6320: výraz filtru výjimky je konstanta EXCEPTION_EXECUTE_HANDLER. To může maskovat výjimky, které nebyly určeny ke zpracování  
  
 Toto upozornění signalizuje vedlejším účinkem použití konstanta EXCEPTION_EXECUTE_HANDLER v blok __except. V tomto případě příkaz v \_blok _except bude vždy bude provedena pro zpracování výjimek, včetně výjimek, které jste nechtěli pro zpracování v určité funkce. Doporučujeme zkontrolovat, zda výjimku před její zpracování.  
  
## <a name="example"></a>Příklad  
 Následující kód vygeneruje toto upozornění, protože __except blokovat se pokusí zpracovat výjimky, které všechny typy:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Chcete-li opravit toto upozornění, použijte `GetExceptionCode` vyhledat konkrétní výjimce před její zpracování, jak je znázorněno v následujícím kódu:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>Viz také  
 [try-except – příkaz](http://msdn.microsoft.com/library/30d60071-ea49-4bfb-a8e6-7a420de66381)



