---
title: C28105
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
author: corob-msft
ms.author: corob
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 35f138288cc46e1b7a4be34b530f07df7f66caff
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 02/15/2020
ms.locfileid: "77270189"
---
# <a name="c28105"></a>C28105
Upozornění C28105: únik prostředku z důvodu výjimky

 Zadaný prostředek není uvolněn, pokud je vyvolána výjimka. Příkaz určený cestou může vyvolat výjimku. Toto upozornění je podobné upozornění [C28103](../code-quality/c28103.md), s výjimkou případů, kdy v tomto případě je zahrnuta výjimka.

## <a name="example"></a>Příklad
 Následující příklad kódu vygeneruje toto upozornění:

```cpp
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

 Následující příklad kódu předchází tomuto upozornění:

```cpp
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```
