---
title: C28105
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: bcd98a6e49b980719b458ebbb79090b0a3bfb587
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 10/07/2019
ms.locfileid: "72010656"
---
# <a name="c28105"></a>C28105
Upozornění C28105: Nevrácení prostředku z důvodu výjimky

 Zadaný prostředek není uvolněn, pokud je vyvolána výjimka. Příkaz určený cestou může vyvolat výjimku. Toto upozornění je podobné upozornění [C28103](../code-quality/c28103.md), s výjimkou případů, kdy v tomto případě je zahrnuta výjimka.

## <a name="example"></a>Příklad
 Následující příklad kódu vygeneruje toto upozornění:

```
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

 Následující příklad kódu předchází tomuto upozornění:

```
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```