---
title: C28105
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: c0906c1e876a13049dfe1d1e7727c22528f8e8ed
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 04/23/2019
ms.locfileid: "62570389"
---
# <a name="c28105"></a>C28105
Upozornění C28105: Nevrácení prostředku z důvodu výjimky

 Zadaný prostředek není uvolněn, pokud je vyvolána výjimka. Příkaz určený argumentem cesta může vyvolat výjimku. Toto upozornění je podobný upozornění [C28103](../code-quality/c28103.md), s tím rozdílem, že v tomto případě se jedná výjimku.

## <a name="example"></a>Příklad
 Následující příklad kódu generuje toto upozornění:

```
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

 Následující příklad kódu se vyhnete toto upozornění:

```
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```