---
title: C28198
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 0867c088e4bfb01a6b1ba9eeb75a7dc91c1321b5
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 12/06/2019
ms.locfileid: "74878876"
---
# <a name="c28198"></a>C28198
upozornění C28198: Možné nevrácení paměti z důvodu výjimky.

 Toto upozornění znamená, že přidělená paměť není uvolněna po vyvolání výjimky. Příkaz na konci cesty může vyvolat výjimku. Paměť byla předána funkci, která mohla uložit kopii pro pozdější uvolnění.

 Toto upozornění je velmi podobné upozornění [C28197](../code-quality/c28197.md). Poznámky, které jsou doporučeny pro použití s upozorněním [C28197](../code-quality/c28197.md) , lze také použít zde.

## <a name="example"></a>Příklad
 Následující příklad kódu vygeneruje toto upozornění:

```cpp
char *p1 = new char[10];
char *p2 = new char[10];

test(p1);   // does not save a copy of p

delete[] p2;
delete[] p1;
```

 Následující příklad kódu předchází tomuto upozornění:

```cpp
char *p1 = new char[10];
char *p2 = NULL;

test(p1);   // does not save a copy of p
try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
```
