---
title: C28105
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: f6a0b92c67840343a7ae1ea0986b27c76375e2e1
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 12/06/2019
ms.locfileid: "74879071"
---
# <a name="c28105"></a>C28105
Upozornění C28105: únik prostředku z důvodu výjimky

 Zadaný prostředek není uvolněn, pokud je vyvolána výjimka. Příkaz určený cestou může vyvolat výjimku. Toto upozornění je podobné upozornění [C28103](../code-quality/c28103.md), s výjimkou případů, kdy v tomto případě je zahrnuta výjimka.

## <a name="example"></a>Příklad
 Následující příklad kódu vygeneruje toto upozornění:

```cpp
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

 Následující příklad kódu předchází tomuto upozornění:

```cpp
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```
