---
title: C28198
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 668c1104cde1a39896082b8877e7b6c3b10ad23c
ms.sourcegitcommit: 21d667104199c2493accec20c2388cf674b195c3
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 02/08/2019
ms.locfileid: "55913584"
---
# <a name="c28198"></a>C28198
upozornění C28198: Možná vzniká nevrácení paměti z důvodu výjimky.

 Toto upozornění signalizuje, že, který přidělenou paměť není uvolnění poté, co je vyvolána výjimka. Příkaz na konci cesty může vyvolat výjimku. Paměť byla předána funkci, která může uložit kopii být později uvolněna.

 Toto upozornění je velmi podobná upozornění [C28197](../code-quality/c28197.md). Poznámky, které se doporučují pro použití s upozorněním [C28197](../code-quality/c28197.md) je také možné použít.

## <a name="example"></a>Příklad
 Následující příklad kódu generuje toto upozornění:

```
char *p1 = new char[10];
char *p2 = new char[10];

test(p1);   // does not save a copy of p

delete[] p2;
delete[] p1;
```

 Následující příklad kódu se vyhnete toto upozornění:

```
char *p1 = new char[10];
char *p2 = NULL;

test(p1);   // does not save a copy of p
try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
```